### ISSUE TITLE
Feature Request - Authorization

### ISSUE THREAD

**Issue by distortia** [MikaAK/trello-elixir#1]
I really dig the wrapper, its simple and easy to use. However, right now, it only works for public boards.
It would be great if we could add authorization to the package so we can access private boards.

thanks!
Nick

**Comment by MikaAK** [comment]
It actually does work on private boards provided you already have both a key and secret! After reading the docs I realize I made a mistake on naming in my lib and everything is pretty much named `secret` which makes it hard to tell 😆. So the `:secret` in your config is actually your key from trello and then each method takes in `secret` as your secondary param! This allows you to pass in a user generated secret from going through auth and you can access private boards. I'll add in a method this weekend to generate the authorization link though to make this easier 😄

**Comment by distortia** [comment]
Awesome dude!
Thanks a ton!

**Comment by MikaAK** [comment]
Added by b4dfa6f, `Trello.generate_auth_url(%{scope: "read,write,account", response_type: "token"})`. I have plans to support OAuth as well but I need to look into it further 😃

**Comment by distortia** [comment]
Awesome dude! Thanks a ton!
